package Interfaces;

import Clases.datosAsignatura;
import Operaciones.Operaciones;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class AgregarRamo extends javax.swing.JFrame {

    Operaciones op = new Operaciones();
    datosAsignatura da = new datosAsignatura();
    
    int cont = 0;
    int x, y;
    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    Color naranjo = new Color(255, 120, 0);
    
    public AgregarRamo() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 820, 540);
        //setLocationRelativeTo(null);
        txtPondPractico.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo_Agregar = new javax.swing.JPanel();
        PanelMenu_Agregar = new javax.swing.JPanel();
        home2 = new javax.swing.JButton();
        PanelInformacion_Agregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEvPracticas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPondPractico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        modoAprob = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtPondTeorico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEvTeoricas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PanelLogo_Agregar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Panel_cerrMin = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo_Agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu_Agregar.setBackground(new java.awt.Color(0, 18, 50));
        PanelMenu_Agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuPrincipal.png"))); // NOI18N
        home2.setBorder(null);
        home2.setBorderPainted(false);
        home2.setContentAreaFilled(false);
        home2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuPrincipal2.png"))); // NOI18N
        home2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuPrincipal2.png"))); // NOI18N
        home2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        home2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        PanelMenu_Agregar.add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        PanelFondo_Agregar.add(PanelMenu_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 540));

        PanelInformacion_Agregar.setBackground(new java.awt.Color(32, 47, 90));
        PanelInformacion_Agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo de Aprobación");
        PanelInformacion_Agregar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        txtHoras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtHoras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoras.setBorder(null);
        txtHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasKeyTyped(evt);
            }
        });
        PanelInformacion_Agregar.add(txtHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 50, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("%");
        PanelInformacion_Agregar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        PanelInformacion_Agregar.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Evaluciones Prácticas");
        PanelInformacion_Agregar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        txtEvPracticas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtEvPracticas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEvPracticas.setBorder(null);
        txtEvPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEvPracticasActionPerformed(evt);
            }
        });
        txtEvPracticas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEvPracticasKeyTyped(evt);
            }
        });
        PanelInformacion_Agregar.add(txtEvPracticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 50, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Horas");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        PanelInformacion_Agregar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ponderación Práctico");
        PanelInformacion_Agregar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txtPondPractico.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtPondPractico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPondPractico.setBorder(null);
        PanelInformacion_Agregar.add(txtPondPractico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 50, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Asignatura ");
        PanelInformacion_Agregar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        modoAprob.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        modoAprob.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "            ---SELECCIONAR---", "TEORICO - PRACTICO en Conjunto", "TEORICO - PRACTICO por Separado" }));
        modoAprob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoAprobActionPerformed(evt);
            }
        });
        PanelInformacion_Agregar.add(modoAprob, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ponderación Teórico");
        PanelInformacion_Agregar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        txtPondTeorico.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtPondTeorico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPondTeorico.setBorder(null);
        txtPondTeorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPondTeoricoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPondTeoricoMouseExited(evt);
            }
        });
        txtPondTeorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPondTeoricoActionPerformed(evt);
            }
        });
        txtPondTeorico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPondTeoricoKeyTyped(evt);
            }
        });
        PanelInformacion_Agregar.add(txtPondTeorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 50, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Evaluciones Teóricas");
        PanelInformacion_Agregar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("%");
        PanelInformacion_Agregar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("%");
        PanelInformacion_Agregar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        txtEvTeoricas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtEvTeoricas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEvTeoricas.setBorder(null);
        txtEvTeoricas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEvTeoricasKeyTyped(evt);
            }
        });
        PanelInformacion_Agregar.add(txtEvTeoricas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 50, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nivel");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        PanelInformacion_Agregar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        txtNivel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtNivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNivel.setBorder(null);
        txtNivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNivelKeyTyped(evt);
            }
        });
        PanelInformacion_Agregar.add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 50, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("%");
        PanelInformacion_Agregar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add3.png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add2.png"))); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add2.png"))); // NOI18N
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelInformacion_Agregar.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Press enter, para calcular pond Practica");
        PanelInformacion_Agregar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(".");
        PanelInformacion_Agregar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("¡");
        PanelInformacion_Agregar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        PanelFondo_Agregar.add(PanelInformacion_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 730, 350));

        PanelLogo_Agregar.setBackground(new java.awt.Color(204, 204, 204));
        PanelLogo_Agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo4.png"))); // NOI18N
        PanelLogo_Agregar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo6.png"))); // NOI18N
        PanelLogo_Agregar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 150, 90));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("2017");
        PanelLogo_Agregar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        PanelFondo_Agregar.add(PanelLogo_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 730, 160));

        Panel_cerrMin.setBackground(new java.awt.Color(255, 255, 255));
        Panel_cerrMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_cerrMinMouseDragged(evt);
            }
        });
        Panel_cerrMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_cerrMinMousePressed(evt);
            }
        });
        Panel_cerrMin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Minus_Math__25px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/min2.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/min2.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel_cerrMin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Delete_25px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete4.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete4.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Panel_cerrMin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 30));

        PanelFondo_Agregar.add(Panel_cerrMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 730, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setExtendedState(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int resp = JOptionPane.showConfirmDialog(null,
                "Los Datos no guardado se eliminarán.\n ¿Desea salir igualmente?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.OK_OPTION == resp) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtEvPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEvPracticasActionPerformed

    }//GEN-LAST:event_txtEvPracticasActionPerformed

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered

        //Color naranjo = new Color(255, 120, 0);
        jLabel16.setForeground(naranjo);
        jLabel16.setText("Agregar Asignatura");
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited

        jLabel16.setForeground(Color.WHITE);
        jLabel16.setText(".");
    }//GEN-LAST:event_jButton4MouseExited

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed

        if (cont == 0) {
            int resp = JOptionPane.showConfirmDialog(null,
                    "Los Datos no guardado se eliminarán.\n ¿Desea ir al Menú principal igualmente?",
                    "Volver Menu Principal", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.OK_OPTION == resp) {
                this.dispose();
                PaginaPrincipal pag = new PaginaPrincipal();
                pag.setTitle("PAGINA PRINCIPAL");
                pag.setVisible(true);
            }
        } else {

            this.dispose();
            PaginaPrincipal pag = new PaginaPrincipal();
            pag.setTitle("PAGINA PRINCIPAL");
            pag.setVisible(true);
            cont = 0;
        }
    }//GEN-LAST:event_home2ActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        op.validarTextoNombre(txtNombre.getText(), evt);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void modoAprobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoAprobActionPerformed

        if (modoAprob.getSelectedItem().equals("TEORICO - PRACTICO por Separado")) {
            txtPondTeorico.setText("");
            txtPondPractico.setText("");
        }
        if (modoAprob.getSelectedItem().equals("TEORICO - PRACTICO en Conjunto")) {
            txtPondTeorico.setText("");
            txtPondPractico.setText("");
        }
    }//GEN-LAST:event_modoAprobActionPerformed

    private void txtPondTeoricoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPondTeoricoKeyTyped

        //DecimalFormat formatter = new DecimalFormat("#.##");  PARA PONER SOLO 1 DECIMAL 
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9') && c != KeyEvent.VK_PERIOD) {
            evt.consume();
        }

        if ((c == KeyEvent.VK_PERIOD) && txtPondTeorico.getText().contains(".")) {
            evt.consume();
        }
        if (txtPondTeorico.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPondTeoricoKeyTyped

    private void txtPondTeoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPondTeoricoActionPerformed

        if (!txtPondTeorico.getText().equals("") && txtPondTeorico.getText().charAt(0) != '.') {
            if (Double.valueOf(txtPondTeorico.getText()) <= 100) {
                double pondP = 100 - Double.parseDouble(txtPondTeorico.getText());
                txtPondPractico.setText(String.valueOf(pondP));

                txtEvPracticas.setText("");
                txtEvPracticas.setEditable(true);
                txtEvTeoricas.setText("");
                txtEvTeoricas.setEditable(true);
            }
        }
        if (!txtPondTeorico.getText().equals("") && txtPondTeorico.getText().charAt(0) != '.') {
            if (Double.valueOf(txtPondTeorico.getText()) > 100) {
                jLabel13.setText("Introduce Ponderacion menor a 100");

            } else if (Double.valueOf(txtPondTeorico.getText()) == 100) {
                txtEvPracticas.setText("0");
                txtEvPracticas.setEditable(false);
            } else if (Double.valueOf(txtPondPractico.getText()) == 100) {
                txtEvTeoricas.setText("0");
                txtEvTeoricas.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtPondTeoricoActionPerformed

    private void txtPondTeoricoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPondTeoricoMouseEntered

        //Color naranjo = new Color(255, 120, 0);
        jLabel13.setForeground(naranjo);
        jLabel17.setForeground(naranjo);

    }//GEN-LAST:event_txtPondTeoricoMouseEntered

    private void txtPondTeoricoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPondTeoricoMouseExited

        jLabel13.setForeground(Color.WHITE);
        jLabel17.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtPondTeoricoMouseExited

    private void txtEvTeoricasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEvTeoricasKeyTyped

        op.validarCantNotas(txtEvTeoricas.getText(), evt);
    }//GEN-LAST:event_txtEvTeoricasKeyTyped

    private void txtEvPracticasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEvPracticasKeyTyped

        op.validarCantNotas(txtEvPracticas.getText(), evt);
    }//GEN-LAST:event_txtEvPracticasKeyTyped

    private void txtHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasKeyTyped

        op.validarCantHoras(txtHoras.getText(), evt);
    }//GEN-LAST:event_txtHorasKeyTyped

    private void txtNivelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNivelKeyTyped

        op.validarCantHoras(txtNivel.getText(), evt);
    }//GEN-LAST:event_txtNivelKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (!txtNombre.getText().equals("") && !txtPondTeorico.getText().equals("") && !txtPondPractico.getText().equals("") && !txtEvTeoricas.getText().equals("")
                && !txtEvPracticas.getText().equals("") && !txtHoras.getText().equals("") && !txtNivel.getText().equals("") && !modoAprob.getSelectedItem().equals(0)) {
            if (verificarRamo(txtNombre.getText())) {

                JOptionPane.showMessageDialog(this, "La asignatura ya se encuentra registrada");

            } else {
                if ((Double.parseDouble(txtPondTeorico.getText()) + Double.parseDouble(txtPondPractico.getText())) == 100) {

                    if (txtPondTeorico.getText().equals("100")) {
                        da.setTipo("Teórico");
                        op.agregarAsign(txtNombre.getText(), da.getTipo(), Integer.parseInt(txtEvTeoricas.getText()), Integer.parseInt(txtEvPracticas.getText()), Double.parseDouble(txtPondTeorico.getText()), Double.parseDouble(txtPondPractico.getText()), Integer.parseInt(txtHoras.getText()), Integer.parseInt(txtNivel.getText()));
                        JOptionPane.showMessageDialog(this, "Asignatura registrada!");
                        txtNombre.setEditable(false);
                        txtPondTeorico.setEditable(false);
                        txtHoras.setEditable(false);
                        txtEvTeoricas.setEditable(false);
                        txtEvPracticas.setEditable(false);
                        txtNivel.setEditable(false);
                        modoAprob.setEnabled(false);
                        cont++;
                    }else if (txtPondTeorico.getText().equals("0")) {
                        da.setTipo("Práctico");
                        op.agregarAsign(txtNombre.getText(), da.getTipo(), Integer.parseInt(txtEvTeoricas.getText()), Integer.parseInt(txtEvPracticas.getText()), Double.parseDouble(txtPondTeorico.getText()), Double.parseDouble(txtPondPractico.getText()), Integer.parseInt(txtHoras.getText()), Integer.parseInt(txtNivel.getText()));
                        JOptionPane.showMessageDialog(this, "Asignatura registrada!");
                        txtNombre.setEditable(false);
                        txtPondTeorico.setEditable(false);
                        txtHoras.setEditable(false);
                        txtEvTeoricas.setEditable(false);
                        txtEvPracticas.setEditable(false);
                        txtNivel.setEditable(false);
                        modoAprob.setEnabled(false);
                        cont++;
                    } 
                    if (!txtPondTeorico.getText().equals("0") && !txtPondTeorico.getText().equals("100")){
                        op.agregarAsign(txtNombre.getText(), modoAprob.getSelectedItem().toString(), Integer.parseInt(txtEvTeoricas.getText()), Integer.parseInt(txtEvPracticas.getText()), Double.parseDouble(txtPondTeorico.getText()), Double.parseDouble(txtPondPractico.getText()), Integer.parseInt(txtHoras.getText()), Integer.parseInt(txtNivel.getText()));
                        JOptionPane.showMessageDialog(this, "Asignatura registrada!");
                        txtNombre.setEditable(false);
                        txtPondTeorico.setEditable(false);
                        txtHoras.setEditable(false);
                        txtEvTeoricas.setEditable(false);
                        txtEvPracticas.setEditable(false);
                        txtNivel.setEditable(false);
                        modoAprob.setEnabled(false);
                        cont++;
                    }
                    
                } else if ((Double.parseDouble(txtPondTeorico.getText()) + Double.parseDouble(txtPondPractico.getText())) != 100) {
                    JOptionPane.showMessageDialog(null, "Ponderación no suma 100%",
                            "ERROR", JOptionPane.WARNING_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos",
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Panel_cerrMinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cerrMinMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_Panel_cerrMinMousePressed

    private void Panel_cerrMinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cerrMinMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_Panel_cerrMinMouseDragged

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        //Color naranjo = new Color(255, 120, 0);
        jLabel16.setForeground(naranjo);
        jLabel16.setText("Horas de la Asignatura");
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel16.setForeground(Color.WHITE);
        jLabel16.setText(".");
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        jLabel16.setForeground(naranjo);
        jLabel16.setText("Nivel de la Asignatura");
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        jLabel16.setForeground(Color.WHITE);
        jLabel16.setText(".");
    }//GEN-LAST:event_jLabel11MouseExited

    private boolean verificarRamo(String nombre) {
        return op.verRamo(nombre);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarRamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarRamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarRamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarRamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarRamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo_Agregar;
    private javax.swing.JPanel PanelInformacion_Agregar;
    private javax.swing.JPanel PanelLogo_Agregar;
    private javax.swing.JPanel PanelMenu_Agregar;
    private javax.swing.JPanel Panel_cerrMin;
    private javax.swing.JButton home2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox modoAprob;
    private javax.swing.JTextField txtEvPracticas;
    private javax.swing.JTextField txtEvTeoricas;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPondPractico;
    private javax.swing.JTextField txtPondTeorico;
    // End of variables declaration//GEN-END:variables
}
