package Interfaces;

import Clases.*;
import Operaciones.Operaciones;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class InterfazAsignaturas extends javax.swing.JFrame {

    interfazSimple s = new interfazSimple();
    InterfazMixto m = new InterfazMixto();
    PaginaPrincipal pag = new PaginaPrincipal();

    String ruta;
    int ejex, ejey;
    datosAsignatura da = new datosAsignatura();
    Operaciones op = new Operaciones();
    NotasPracticas np = new NotasPracticas();
    NotasTeoricas nt = new NotasTeoricas();
    PondPracticas pp = new PondPracticas();
    PondTeoricas pt = new PondTeoricas();
    NotasFinales nf = new NotasFinales();

    int x, y;
    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

    public InterfazAsignaturas() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        //setLocationRelativeTo(null);
        this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 1090, 640);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        inicioBotones();
    }

    private void inicioBotones() {
        switch (op.ConsultaListaRamos().size()) {
            case 10:
                asign10.setText(op.ConsultaListaRamos().get(9).getNombre());
            case 9:
                asign9.setText(op.ConsultaListaRamos().get(8).getNombre());
            case 8:
                asign8.setText(op.ConsultaListaRamos().get(7).getNombre());
            case 7:
                asign7.setText(op.ConsultaListaRamos().get(6).getNombre());
            case 6:
                asign6.setText(op.ConsultaListaRamos().get(5).getNombre());
            case 5:
                asign5.setText(op.ConsultaListaRamos().get(4).getNombre());
            case 4:
                asign4.setText(op.ConsultaListaRamos().get(3).getNombre());
            case 3:
                asign3.setText(op.ConsultaListaRamos().get(2).getNombre());
            case 2:
                asign2.setText(op.ConsultaListaRamos().get(1).getNombre());
            case 1:
                asign1.setText(op.ConsultaListaRamos().get(0).getNombre());
            case 0:
                break;
        }
        switch (op.ConsultaListaRamos().size()) {
            case 0:
                asign1.setVisible(false);
            case 1:
                asign2.setVisible(false);
            case 2:
                asign3.setVisible(false);
            case 3:
                asign4.setVisible(false);
            case 4:
                asign5.setVisible(false);
            case 5:
                asign6.setVisible(false);
            case 6:
                asign7.setVisible(false);
            case 7:
                asign8.setVisible(false);
            case 8:
                asign9.setVisible(false);
            case 9:
                asign10.setVisible(false);
            case 10:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo_Simple = new javax.swing.JPanel();
        PanelPestañas = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Horario = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        PanelLogo_Simple = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Panel_cerrMin = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelMenu_Ramos2 = new javax.swing.JPanel();
        asign1 = new javax.swing.JButton();
        asign2 = new javax.swing.JButton();
        asign3 = new javax.swing.JButton();
        asign4 = new javax.swing.JButton();
        asign5 = new javax.swing.JButton();
        asign6 = new javax.swing.JButton();
        asign7 = new javax.swing.JButton();
        asign8 = new javax.swing.JButton();
        asign9 = new javax.swing.JButton();
        asign10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo_Simple.setBackground(new java.awt.Color(0, 18, 50));
        PanelFondo_Simple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPestañas.setBackground(new java.awt.Color(32, 47, 90));
        PanelPestañas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(32, 47, 90));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton3.setText("Agregar Horario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 740, 430));

        jScrollPane2.setViewportView(jPanel5);

        jTabbedPane1.addTab("Horario", jScrollPane2);

        jPanel7.setBackground(new java.awt.Color(32, 47, 90));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Horario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1º        8:30 a 9:30", null, null, null, null, null},
                {"2º        9:40 a 10:40", null, null, null, null, null},
                {"3º        10:50 a 11:50", null, null, null, null, null},
                {"4º        12:00 a 13:00", null, null, null, null, null},
                {"Alm      13:10 a 14:10", null, null, null, null, null},
                {"5º        14:30 a 15:30", null, null, null, null, null},
                {"6º        15:40 a 16:40", null, null, null, null, null},
                {"7º        16:50 a 17:50", null, null, null, null, null},
                {"8º        18:00 a 19:00", null, null, null, null, null},
                {"9º        19:10 a 20:10", null, null, null, null, null},
                {"10º      20:20 a 21:20", null, null, null, null, null}
            },
            new String [] {
                "Periodo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes"
            }
        ));
        Horario.setRowHeight(39);
        jScrollPane6.setViewportView(Horario);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 450));

        jButton6.setText("excel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, 20));

        jScrollPane3.setViewportView(jPanel7);

        jTabbedPane1.addTab("Planificar Horario Academico", jScrollPane3);

        jPanel4.setBackground(new java.awt.Color(32, 47, 90));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane4.setViewportView(jPanel4);

        jTabbedPane1.addTab("Por definir", jScrollPane4);

        jPanel3.setBackground(new java.awt.Color(32, 47, 90));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane5.setViewportView(jPanel3);

        jTabbedPane1.addTab("Por definir", jScrollPane5);

        PanelPestañas.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 480));

        PanelFondo_Simple.add(PanelPestañas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 900, 480));

        PanelLogo_Simple.setBackground(new java.awt.Color(204, 204, 204));
        PanelLogo_Simple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo6.png"))); // NOI18N
        PanelLogo_Simple.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 150, 90));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo7.png"))); // NOI18N
        PanelLogo_Simple.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("2017");
        PanelLogo_Simple.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        PanelFondo_Simple.add(PanelLogo_Simple, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 900, 130));

        Panel_cerrMin.setBackground(new java.awt.Color(255, 255, 255));
        Panel_cerrMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_cerrMinMouseDragged(evt);
            }
        });
        Panel_cerrMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_cerrMinMousePressed(evt);
            }
        });
        Panel_cerrMin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Minus_Math__25px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/min2.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/min2.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel_cerrMin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Delete_25px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete4.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete4.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Panel_cerrMin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 30, 30));

        PanelFondo_Simple.add(Panel_cerrMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 900, 30));

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuPrincipal.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuPrincipal2.png"))); // NOI18N
        jButton5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuPrincipal2.png"))); // NOI18N
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 30, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gmail.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gmail1.png"))); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gmail1.png"))); // NOI18N
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 30, 30));

        jButton8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intranet.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intranet2.png"))); // NOI18N
        jButton8.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intranet2.png"))); // NOI18N
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 30, 30));

        jButton9.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campus.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campus1.png"))); // NOI18N
        jButton9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campus1.png"))); // NOI18N
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 30, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        PanelFondo_Simple.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 140));

        PanelMenu_Ramos2.setBackground(new java.awt.Color(0, 18, 50));
        PanelMenu_Ramos2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        asign1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign1.setForeground(new java.awt.Color(255, 255, 255));
        asign1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign1.setText("jButton4");
        asign1.setBorder(null);
        asign1.setBorderPainted(false);
        asign1.setContentAreaFilled(false);
        asign1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign1ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 40));

        asign2.setBackground(new java.awt.Color(255, 255, 255));
        asign2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign2.setForeground(new java.awt.Color(255, 255, 255));
        asign2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign2.setText("jButton4");
        asign2.setBorder(null);
        asign2.setBorderPainted(false);
        asign2.setContentAreaFilled(false);
        asign2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign2ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 40));

        asign3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign3.setForeground(new java.awt.Color(255, 255, 255));
        asign3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign3.setText("jButton4");
        asign3.setBorder(null);
        asign3.setBorderPainted(false);
        asign3.setContentAreaFilled(false);
        asign3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign3ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 40));

        asign4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign4.setForeground(new java.awt.Color(255, 255, 255));
        asign4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign4.setText("jButton4");
        asign4.setBorder(null);
        asign4.setBorderPainted(false);
        asign4.setContentAreaFilled(false);
        asign4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign4ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 40));

        asign5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign5.setForeground(new java.awt.Color(255, 255, 255));
        asign5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign5.setText("jButton4");
        asign5.setBorder(null);
        asign5.setBorderPainted(false);
        asign5.setContentAreaFilled(false);
        asign5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign5ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 40));

        asign6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign6.setForeground(new java.awt.Color(255, 255, 255));
        asign6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign6.setText("jButton4");
        asign6.setBorder(null);
        asign6.setBorderPainted(false);
        asign6.setContentAreaFilled(false);
        asign6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign6ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, 40));

        asign7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign7.setForeground(new java.awt.Color(255, 255, 255));
        asign7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign7.setText("jButton4");
        asign7.setBorder(null);
        asign7.setBorderPainted(false);
        asign7.setContentAreaFilled(false);
        asign7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign7ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 140, 40));

        asign8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign8.setForeground(new java.awt.Color(255, 255, 255));
        asign8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign8.setText("jButton4");
        asign8.setBorder(null);
        asign8.setBorderPainted(false);
        asign8.setContentAreaFilled(false);
        asign8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign8ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 140, 40));

        asign9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign9.setForeground(new java.awt.Color(255, 255, 255));
        asign9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign9.setText("jButton4");
        asign9.setBorder(null);
        asign9.setBorderPainted(false);
        asign9.setContentAreaFilled(false);
        asign9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign9ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 140, 40));

        asign10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        asign10.setForeground(new java.awt.Color(255, 255, 255));
        asign10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ramos5.png"))); // NOI18N
        asign10.setText("jButton4");
        asign10.setBorder(null);
        asign10.setBorderPainted(false);
        asign10.setContentAreaFilled(false);
        asign10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asign10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        asign10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asign10ActionPerformed(evt);
            }
        });
        PanelMenu_Ramos2.add(asign10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 140, 40));

        jScrollPane1.setViewportView(PanelMenu_Ramos2);

        PanelFondo_Simple.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo_Simple, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo_Simple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int resp = JOptionPane.showConfirmDialog(null,
                "Los Datos no guardado se eliminarán.\n ¿Desea salir igualmente?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.OK_OPTION == resp) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        this.dispose();
        pag.setTitle("PAGINA PRINCIPAL");
        pag.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void asign1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign1ActionPerformed
        try {
            asignatura(asign1.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_asign1ActionPerformed

    private void asign2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign2ActionPerformed

        try {
            asignatura(asign2.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign2ActionPerformed

    private void asign3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign3ActionPerformed

        try {
            asignatura(asign3.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign3ActionPerformed

    private void asign4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign4ActionPerformed

        try {

            asignatura(asign4.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign4ActionPerformed

    private void asign5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign5ActionPerformed

        try {
            asignatura(asign5.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign5ActionPerformed

    private void asign6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign6ActionPerformed

        try {

            asignatura(asign6.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign6ActionPerformed

    private void asign7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign7ActionPerformed

        try {

            asignatura(asign7.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign7ActionPerformed

    private void asign8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign8ActionPerformed

        try {

            asignatura(asign8.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign8ActionPerformed

    private void asign9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign9ActionPerformed

        try {

            asignatura(asign9.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign9ActionPerformed

    private void asign10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asign10ActionPerformed

        try {

            asignatura(asign10.getText());
        } catch (IOException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asign10ActionPerformed

    private void Panel_cerrMinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cerrMinMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_Panel_cerrMinMousePressed

    private void Panel_cerrMinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_cerrMinMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_Panel_cerrMinMouseDragged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de imagen", "jpg", "png");
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileFilter(filtro);
        int option = seleccionar.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            ruta = seleccionar.getSelectedFile().getPath();
            System.out.println(ruta);
            ImageIcon icon = new ImageIcon(ruta);

            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
            jLabel1.setIcon(icono);
            this.repaint();

        } else {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setText("INTRANET");
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setText(".");
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setText("CAMPUS VIRTUAL");
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setText(".");
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setText("UFROMAIL");
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setText(".");
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        goToURL("https://intranet.ufro.cl/");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        goToURL("https://campusvirtual.ufro.cl");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        goToURL("https://www.google.com/intl/es/gmail/about/#");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> horario = new ArrayList<String>();
        for (int i = 0; i < Horario.getRowCount(); i++) {
            for (int j = 0; j < Horario.getColumnCount(); j++) {
                String a = (String) Horario.getValueAt(i, j);
                String b = (String) Horario.getValueAt(i, 1);
                String c = (String) Horario.getValueAt(i, 2);
                String d = (String) Horario.getValueAt(i, 3);
                String f = (String) Horario.getValueAt(i, 4);
                String g = (String) Horario.getValueAt(i, 5);
                //String h = (String) Horario.getValueAt(i, 6);

                horario.add(a);
                //System.out.println(a);
            }

        }
        for (int i = 0; i < Horario.getRowCount(); i++) {
                System.out.println(horario.get(i));
        }
        Excel ex = new Excel();
        try {
            ex.exportar(horario);
        } catch (IOException ex1) {
            Logger.getLogger(InterfazAsignaturas.class.getName()).log(Level.SEVERE, null, ex1);
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void asignatura(String nombre) throws IOException {
        if (op.verTipo(nombre).equals("TEORICO - PRACTICO por Separado") || op.verTipo(nombre).equals("TEORICO - PRACTICO en Conjunto")) {

            da = op.SelectAllDataFromAsignatura(nombre);
            np = op.notasPracticas(nombre);
            nt = op.notasTeoricas(nombre);
            pp = op.ponderacionPrac(nombre);
            pt = op.ponderacionTeo(nombre);
            nf = op.notasFinales(nombre);

            m.ingresarRamo((datosAsignatura) da, (NotasPracticas) np, (NotasTeoricas) nt, (PondPracticas) pp, (PondTeoricas) pt, (NotasFinales) nf);

            m.setVisible(true);
        } else {
            if (op.verTipo(nombre).equals("Teórico") || op.verTipo(nombre).equals("Práctico")) {

                da = op.SelectAllDataFromAsignatura(nombre);
                np = op.notasPracticas(nombre);
                nt = op.notasTeoricas(nombre);
                pp = op.ponderacionPrac(nombre);
                pt = op.ponderacionTeo(nombre);
                nf = op.notasFinales(nombre);

                s.ingresarRamo((datosAsignatura) da, (NotasPracticas) np, (NotasTeoricas) nt, (PondPracticas) pp, (PondTeoricas) pt, (NotasFinales) nf);

                s.setVisible(true);

            }
        }
        this.dispose();
    }

    public void goToURL(String URL) {
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI uri = new java.net.URI(URL);
                    desktop.browse(uri);
                } catch (URISyntaxException | IOException ex) {
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAsignaturas().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Horario;
    private javax.swing.JPanel PanelFondo_Simple;
    private javax.swing.JPanel PanelLogo_Simple;
    private javax.swing.JPanel PanelMenu_Ramos2;
    public javax.swing.JPanel PanelPestañas;
    private javax.swing.JPanel Panel_cerrMin;
    private javax.swing.JButton asign1;
    private javax.swing.JButton asign10;
    private javax.swing.JButton asign2;
    private javax.swing.JButton asign3;
    private javax.swing.JButton asign4;
    private javax.swing.JButton asign5;
    private javax.swing.JButton asign6;
    private javax.swing.JButton asign7;
    private javax.swing.JButton asign8;
    private javax.swing.JButton asign9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
