package Interfaces;

import Clases.NotasPracticas;
import Clases.NotasTeoricas;
import Clases.PondPracticas;
import Clases.PondTeoricas;
import Clases.datosAsignatura;
import Operaciones.Operaciones;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Felipe
 */
public class PanelAsignaturas extends javax.swing.JPanel {

    Operaciones op = new Operaciones();
    datosAsignatura da = new datosAsignatura();
    NotasPracticas np = new NotasPracticas();
    NotasTeoricas nt = new NotasTeoricas();
    PondPracticas pp = new PondPracticas();
    PondTeoricas pt = new PondTeoricas();

    interfazSimple s = new interfazSimple();
    InterfazMixto m = new InterfazMixto();
    InterfazAsignaturas inter = new InterfazAsignaturas();
    
    public PanelAsignaturas() {

        initComponents();
        
    }

    public JLabel getLabelNivel() {
        return labelNivel;
    }

    public void setLabelNivel(String labelNivel) {
        this.labelNivel.setText(labelNivel);
    }

    public JButton getLabelRamo() {
        return labelRamo;
    }

    public void setLabelRamo(String labelRamo) {
        this.labelRamo.setText(labelRamo);
    }

    public JLabel getLavelHoras() {
        return lavelHoras;
    }

    public void setLavelHoras(String lavelHoras) {
        this.lavelHoras.setText(lavelHoras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNivel = new javax.swing.JLabel();
        lavelHoras = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labelRamo = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Nivel:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Horas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelNivel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelNivel.setText("3");
        jPanel1.add(labelNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 10, -1));

        lavelHoras.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lavelHoras.setText("6");
        jPanel1.add(lavelHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit5.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit4.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit4.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jButton3.setText("editar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelRamo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        labelRamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelRamoActionPerformed(evt);
            }
        });
        jPanel1.add(labelRamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelRamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelRamoActionPerformed
        try {
            asignatura(labelRamo.getText());
        } catch (IOException ex) {
            Logger.getLogger(PanelAsignaturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelRamoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!verificarRamo(labelRamo.getText())) {
            JOptionPane.showMessageDialog(inter, "La asignatura ya se ha eliminado");
        } else {
            int resp = JOptionPane.showConfirmDialog(null,
                    "Los Datos borrados no se podrán recuperar.\n ¿Desea Eliminar Asignatura?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.OK_OPTION == resp) {
                op.borrarRamo(labelRamo.getText());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean verificarRamo(String nombre) {
        return op.verRamo(nombre);
    }

    private void asignatura(String nombre) throws IOException {

        if (op.verTipo(nombre).equals("TEORICO - PRACTICO por Separado") || op.verTipo(nombre).equals("TEORICO - PRACTICO en Conjunto")) {

            da = op.SelectAllDataFromAsignatura(nombre);
            np = op.notasPracticas(nombre);
            nt = op.notasTeoricas(nombre);
            pp = op.ponderacionPrac(nombre);
            pt = op.ponderacionTeo(nombre);

            //m.ingresarRamo((datosAsignatura) da, (NotasPracticas) np, (NotasTeoricas) nt, (PondPracticas) pp, (PondTeoricas) pt);

            //m.setTitle(da.getNombre());
            m.setVisible(true);
        } else {
            if (op.verTipo(nombre).equals("Teórico") || op.verTipo(nombre).equals("Práctico")) {

                da = op.SelectAllDataFromAsignatura(nombre);
                np = op.notasPracticas(nombre);
                nt = op.notasTeoricas(nombre);
                pp = op.ponderacionPrac(nombre);
                pt = op.ponderacionTeo(nombre);

               // s.ingresarRamo((datosAsignatura) da, (NotasPracticas) np, (NotasTeoricas) nt, (PondPracticas) pp, (PondTeoricas) pt);
                //s.setTitle(da.getNombre());
                s.setVisible(true);

            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNivel;
    public javax.swing.JButton labelRamo;
    private javax.swing.JLabel lavelHoras;
    // End of variables declaration//GEN-END:variables
}
